### ISSUE TITLE
Not working on Android 12

### ISSUE THREAD

**Issue by tranhuudang** [mirkancal/pdf_thumbnail#1]
Simple to use as it is, but when I provide my file path, it just shows the background color, and no image is rendered.
![image](https://user-images.githubusercontent.com/96557038/194597152-5ebd404a-9e05-4081-9cc1-2db992c25f74.png)

**Comment by tranhuudang** [comment]
I/flutter (17247): PlatformException(PdfRendererException, io.scer.pdfx.PdfRendererException: Can't open file, Cause: null, Stacktrace: io.scer.pdfx.PdfRendererException: Can't open file
I/flutter (17247): 	at io.scer.pdfx.Messages.openDocumentFile(Messages.kt:73)
I/flutter (17247): 	at dev.flutter.pigeon.Pigeon$PdfxApi$-CC.lambda$setup$1(Pigeon.java:1524)
I/flutter (17247): 	at dev.flutter.pigeon.Pigeon$PdfxApi$$ExternalSyntheticLambda2.onMessage(Unknown Source:2)
I/flutter (17247): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
I/flutter (17247): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (17247): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter (17247): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (17247): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (17247): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (17247): 	at android.os.Looper.loopOnce(Looper.java:201)
I/flutter (17247): 	at android.os

**Comment by mirkancal** [comment]
@tranhuudang are you sure there's a file in that path? You can use `File` constructor and see if you can have an actual `File` object.

final pdfFile = File("/data/user0...")

**Comment by tranhuudang** [comment]
Yes, you are so right about it. I change to a proper file path, and it works. It is great, thank you for sharing such a helpful package.
