### ISSUE TITLE
feat: Load multiple pdf files

### ISSUE THREAD

**Issue by samiissa** [mirkancal/pdf_thumbnail#6]
**Description**
Hi.

I would like to know if this package can load multiple pdf files on the thumbnail view?

**Requirements**

- Show all the pages of a pdf list files

**Comment by mirkancal** [comment]
Hi @samiissa,

I didn't I'd need that, but you can modify package to support that. Try to pass list of paths to _render and open multiple files one by one.

https://github.com/mirkancal/pdf_thumbnail/blob/main/lib/src/pdf_thumbnail.dart#L217

**Comment by samiissa** [comment]
Hi @mirkancal 

Thank you for your response. Yes I saw the _render method and I think I could adapt it to support multiple files.

Thank you for this awesome package!!

Regards,
